### ISSUE TITLE
Загрузка номеров карт

### ISSUE THREAD

**Issue by vchernokulsky** [evil-lab/NFC-VendPay#5]
1) Загрузка номеров карт из файла на флешке
    - Приложение в отдельном потоке проверяет появление файла по определённому пути
    - При появлении файла, останавливаем обработку запросов от аппарата
    - Считываем номера карт и помещаем их в БД (только новые номера карт)
    - Возобновляем обработку запросов от аппарата
2) Загрузка номеров карт через Интернет

**Comment by NataRazmochaeva** [comment]
* проверять номер карты на соответствие HEX-числу
